### ISSUE TITLE
[ENH] Refactor loopflow

### ISSUE THREAD

**Issue by HYChou0515** [HYChou0515/utensil#25]
# Rename

- [x] **Node**
The structural building block of a flow. It has a long life cycle, listening to its parents node and spawn a process to do a job when its parents are ready.
Won’t rename.
Reason: Node is simple. Despite Node does not say anything about its life time, I think it’s ok.

- [x] **NodeProcess**
A function runner, it has a short lift cycle, existing (suicide) when it finished its job.
Renamed as: **NodeWorker**
Reason: It is a worker *for* a node. 

- [x] **NodeProcessFunction**
A configurable function executed by a process. It is strongly related to business logic.
Renamed as: **NodeTask**
Reason: NodeTask may not be very suitable, because it sounds like it is a static task instead of a configurable one.

- [x] **Trigger** and **Triggering**
If a node A triggers another node B, then A is a trigger of B and B is a triggering of A. 
This is VERY confusing. 
Renamed as: **Caller** and **Callee**
Reason: a traditional caller and callee can catch the point that who is calling who. Though the *call* is not including the parameters passed to the function.

- [x] **Parent** and **Child**
If a node A passes parameters to another node B, then A is a parent of B and B is a child of A.
Better than Trigger, but still confusing. Parent and child is wildly used in Tree structure and whether passing parameters or not is not relevant to this traditional definition of parent and child. 
Renamed as: **Sender** and **Receiver**
Reason: Named sender and receiver, then it is expected that something is transmitted between these two nodes.

- [x] **Parent**, the base class of **Parent** and **Trigger**
Originally, Trigger is a derived class of Parent. After renaming, Trigger and Parent should have a separate base class.
Proposal: This base class can be named Parent.
Reason: Trigger and Parent are still a Parent. It is that one is for triggering (calling) and one is for message passing.

- [x] **NodeProcessMeta**
A shared information between Node and NodeProcess
Renamed as : **NodeMeta**
Reason: NodeMeta is simpler and still descriptive.

- [x] **FLOW**, **FLOW_USE**, **FLOW_OR**
https://github.com/HYChou0515/utensil/blob/4d1e34ff686973eb9111eaf9aad3e992d1a2e9da/utensil/loopflow/loopflow.py#L127-L132
Should be a more descriptive term.

# Member Refactor

- [x] **Node.trigger**
https://github.com/HYChou0515/utensil/blob/4d1e34ff686973eb9111eaf9aad3e992d1a2e9da/utensil/loopflow/loopflow.py#L302-L316
~It doesn’t make sense to passed in a value beside the caller.~
Yes, it does. Passed value is used for check some flow conditions to determine whether to be really triggered.

- [x] **ParentSpecifiers**
https://github.com/HYChou0515/utensil/blob/4d1e34ff686973eb9111eaf9aad3e992d1a2e9da/utensil/loopflow/loopflow.py#L169-L179
Since we already have **ParentSpecifier**, do we really need a tuple of it, the **ParentSpecifiers**?

# Exception Class

- [x] So Many `RuntimeError`
Shouldn’t  have any. Change it to a more descriptive class with more information.

# Tests

- [x] Add more test
Without doing it, codecov fails.

**Comment by HYChou0515** [comment]
@kany102030 would you mind check if those new names make sense to you?

**Comment by kany102030** [comment]
> @kany102030 would you mind check if those new names make sense to you?

great! looks reasonable.
